name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente
        run: echo "Configuração do ambiente concluída"

      - name: Instalar dependências
        run: |
          if [ -f "package.json" ]; then
            npm install
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "Nenhum gerenciador de pacotes identificado. Pulando etapa..."
          fi

      - name: Rodar testes
        run: |
          if [ -f "package.json" ]; then
            npm test || echo "Nenhum teste configurado para Node.js"
          elif [ -f "pytest.ini" ]; then
            pytest || echo "Nenhum teste configurado para Python"
          else
            echo "Nenhum teste identificado. Pulando etapa..."
          fi
