name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar ambiente
        run: echo "Configuração do ambiente"

      - name: Rodar testes
        run: echo "Rodando testes"
