name: Deploy FastFood App

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ser deployada'
        required: true
        default: 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Atualizar kubeconfig
        run: aws eks update-kubeconfig --name pollos-hermanos --region us-east-1

      - name: Aplicar Manifests do Kubernetes
        run: kubectl apply -f k8s/fastfood-app.yaml

      - name: Verificar Status do Rollout
        run: kubectl rollout status deployment/fastfood-app -n default
