name: Deploy FastFood App

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Uses the branch provided via workflow_dispatch (or the branch that triggered the event)
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name pollos-hermanos --region us-east-1

      - name: Apply Kubernetes Manifest
        run: kubectl apply -f k8s/fastfood-app.yaml

      - name: Check Rollout Status
        run: kubectl rollout status deployment/fastfood-app -n default
